### ISSUE TITLE
Not compatible with laravel/framework v5.6 and above

### ISSUE THREAD

**Issue by wakqasahmed** [goavega-software/laravel-azure-servicebus-topic#1]
Hi,

Since the dependencies are hardcoded in composer.json to "v5.5", it doesn't work with laravel versions above than 5.5

```
        "illuminate/container": "5.5.*",
        "illuminate/support": "5.5.*",
        "illuminate/encryption": "5.5.*",
```

There can be tagged versions for each of the minor framework upgrade of this package to become compatible with 5.* versions.

**Comment by sn123** [comment]
version 5.6 of the library should work with Laravel 5.6+ (tested with Laravel 5.8).
